title: My Sample Bloc
theme: minima
author: Marvieqa
email: marvieqa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first attempt of blogging. I wonder how this works?!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
